title: Crowdsourcing as a Shortcut to the Technological Singularity
author: Casey Armstrong
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Free E-Book.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
